# Generated by Django 2.1.7 on 2019-03-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ars', '0002_session_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='sesion_key',
            new_name='session_key',
        ),
    ]
