# Generated by Django 2.1.7 on 2019-03-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ars', '0003_auto_20190305_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_number',
        ),
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
