# Generated by Django 2.1.7 on 2019-03-31 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ars', '0007_auto_20190329_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ars.Session'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ars.Session'),
        ),
    ]
