# Generated by Django 2.1.7 on 2019-03-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ars', '0008_auto_20190331_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='qr_link_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
