# Generated by Django 2.1.7 on 2019-04-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ars', '0009_topic_qr_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='presentation_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='presentation_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
